env:
  es6: true
  node: true
  jest: true
extends: 
    - 'eslint:recommended'
    - 'airbnb-base'
    - 'plugin:jest/recommended'
parser: babel-eslint
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  indent:
    - error
    - spaces
  no-console: 0
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
