language: node_js
node_js:
- node
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- make lint
- make coverage-test
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: QOBuvsy/+wo0oQQfXmps8HkE47LOdTSWPIbWHPehTHqlXpUoyGV+vuaGF1NE1hC0U4M+f2VK0WOcnpDcTPodJrkc/30V9Eb1X6waliPIYXPfyuBYvhE9uA9HwzAM8HCbe6Bx0bVZ9f8PnWH9eGPTRf44FsbzfSL6M8jhqbi2ERPOiGiUeudkieZXLInIKMzxJjtZwzG1/c1mG78vrE6Epnl8eDHoDAT0iG0TjjsVz6k20+Cck84LUAHriRlHE7zo9nWHBkO8XLvxVs1lpEFOeWRGDGmtOhlVbdA2VoRzMHTvc5AZKIADsOgjdow09Od1OKh99urvd7O798fyyDQCoyqDbiXrsbFCBAHELdHDlUd3fiwARiOptBwaGGhEUW+CgIIgyX8mGk5o8roy0XPf5eQaqe7vAgYWA2gYC087xtLwKD27QrTDZiLKaOpw7tCkfZWc+c0zoARaG+Y5uIuO6Wec+TmZNpnb1TkckLL1Y/oDWn9/Lts4b+02aDc0VfevWhCP8Co5TIVaRabfbpqyVumd75vvLkw/O5wX/UreUyVdb/xjTc5o7r6R4jORXPecV+OWv9efU4P6xkePt5dgE5jjXI0z4NYqq4MJFDnzjnS+p74JAKLx5NlVD2yub7FRUn2+4SJFeBRuiTiQ5t0K18KJQW3rqM8PhypzdiwWAwE=
  app: mighty-woodland-68609
  run: npm run initDb